### ISSUE TITLE
KO hierarchy is actually a tree

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/KEGG_data_extraction#3]
For the KO hierarchy at  `/data/shared_data/KEGG_KO_hierarchy/results/kegg_ko_edge_df.txt`, I've noticed that K02014 has a single ancestor in this file:
```
$ grep 'K02014' kegg_ko_edge_df.txt
02000 Transporters      K02014
```
However, on the KEGG website, there are two components it is a part of: https://www.genome.jp/kegg-bin/search_brite?option=-a&search_string=K02014, namely it should have as ancestors "Transporters BR:ko02000" and "KEGG orthology BR:ko00001".

Importing the full edge list, I've checked and it appears to be a tree. I.e. it's missing some parts of the hierarchy.

**Comment by chunyuma** [comment]
I guess this issue is fixed so I close it.
